package login.auth.payload.request;

import lombok.Getter;
import lombok.Setter;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import java.util.Set;

@Getter // Getters generated by Lombok
@Setter // Setters generated by Lombok
public class RegisterRequest {

    @NotBlank // Username is mandatory to register
    @Size(min = 3, max = 25) // Username must consist of a minimum of 3 characters and a maximum of 25 characters
    private String username;

    @NotBlank // Email address is mandatory to register
    @Size(max = 50) // Email address must consist of a maximum of 50 characters
    @Email // Validate if provided email address is indeed a email address
    private String email;

    // Set role (standard role: User)
    private Set<String> role;

    @NotBlank // Password is mandatory to register
    @Size(min = 8, max = 125) // Password must consist of a minimum of 8 characters and a maximum of 125 characters
    private String password;
}
