package login.audit.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import javax.persistence.Column;
import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;
import java.util.Date;

@Getter // Getters generated by Lombok
@Setter // Setters generated by Lombok
@MappedSuperclass // Instructing Spring Boot this is the parent class
@EntityListeners(AuditingEntityListener.class)
@JsonIgnoreProperties(
        value = {"createdAt", "updatedAt"},
        allowGetters = true
)
public abstract class Audit {

    @Column( name = "created_at", nullable = false, updatable = false ) // Create column in database with name created_at, is mandatory
    @CreationTimestamp // Annotation to persist timestamp
    private Date createdAt;

    @Column( name = "updated_at", nullable = false ) // Create column in database with name updated_at, is mandatory
    @UpdateTimestamp // Annotation to persist update for timestamp
    private Date updatedAt;
}
